#!/bin/bash

# newdefine
# version 1.3

# Declare the messy dictionary.com function
# This runs only if we can't find the definition on Ding.com

messydict ()
{
# version 1.3

messydmp="$(lynx -dump dictionary.reference.com/browse/"$word")"

cleanedup="$(echo "$messydmp" | head -60 | sed -e 's/^[ \t]*//' -e 's/\[.*\]//g' | sed -r '/^[0-9][0-9]?\.$/ {N;s/\n/ /}')"

firstdef="$(echo "$cleanedup" | sed -nr '/^(noun|verb|adjective)/{:a;N;/\n*\.$/!ba;p;q}')"

if [ -e $word.html ]; then
    isword="$(echo "$messydmp" | grep "no dictionary results")"
    if [ -z "$isword" ]; then
	echo "$firstdef"
	if [[ "$firstdef" == *1.* ]]; then
	    testseconddef="$(echo "$cleanedup" | grep -m1 "^2.*$")"
	    if [ -n "$testseconddef" ]; then
		echo "$testseconddef"
	    else
		seconddef="$(echo "$cleanedup" | sed -nr '/^2\.\s*/{:a;N;/\n*\.$/!ba;p;q}')"
		echo "$seconddef"
	    fi
	else
	    :
	fi
    else
	echo Unable to define $word
    fi
else
    echo "Couldn't look up " $word
fi
}


# Main function (Ding Bictionary script)

word=$1

dmp="$(lynx -dump www.bing.com/search?q=define+"$word")"

cleanup="$(echo "$dmp" | sed -e 's/^[ \t]*//' -e '/\[*\]/d' | tr -cd '\11\12\40-\176')"

def="$(echo "$cleanup" | sed -nr "/^($1)\.?$/{:a;N;/\n^$/!ba;p;q}")"

if [[ "$def" != *1.* ]]; then
    messydict
else
    echo -e "$def"
fi